# Generated by Django 5.1.15 on 2026-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('user', 'User')],
                default='user',
                max_length=20,
                db_index=True,
            ),
        ),
    ]
