# Generated by Django 5.1.15 on 2026-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_local', models.CharField(blank=True, help_text='Local/regional name', max_length=200)),
                ('category', models.CharField(choices=[('grains', 'Grains & Cereals'), ('protein', 'Protein Sources'), ('dairy', 'Dairy & Eggs'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('legumes', 'Legumes & Pulses'), ('nuts_seeds', 'Nuts & Seeds'), ('fats_oils', 'Fats & Oils'), ('beverages', 'Beverages'), ('snacks', 'Snacks & Others')], default='protein', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sugar_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sodium_mg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('serving_size_g', models.DecimalField(decimal_places=1, default=100, help_text='Default serving size in grams', max_digits=6)),
                ('serving_description', models.CharField(blank=True, help_text='e.g., 1 cup, 1 medium', max_length=100)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx'), models.Index(fields=['category'], name='nutrition_f_categor_32643c_idx')],
            },
        ),
    ]
