# Generated by Django 5.1.15 on 2026-07-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='My Meal Plan', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_calories', models.IntegerField()),
                ('target_protein_g', models.IntegerField(default=0)),
                ('target_carbs_g', models.IntegerField(default=0)),
                ('target_fat_g', models.IntegerField(default=0)),
                ('target_water_ml', models.IntegerField(default=2500)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_prompt_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
                ('day_number', models.PositiveSmallIntegerField(default=1, help_text='Day 1–7 within the plan')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('calories', models.IntegerField()),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('recipe_steps', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('foods', models.ManyToManyField(blank=True, related_name='meals', to='nutrition.food')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplanner.mealplan')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['day_number', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('unit', models.CharField(blank=True, help_text='e.g., grams, cups, pieces', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='mealplanner.mealplan')),
            ],
            options={
                'verbose_name': 'Grocery Item',
                'verbose_name_plural': 'Grocery Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='mealplanner.mealplan')),
            ],
            options={
                'verbose_name': 'Favourite Meal',
                'verbose_name_plural': 'Favourite Meals',
                'unique_together': {('user', 'meal_plan')},
            },
        ),
    ]
