import { useQuery } from '@tanstack/react-query'
import { adminService } from '../../services'
import LoadingSpinner from '../../components/LoadingSpinner'
import { Users, Calendar, Cpu, Database, AlertCircle, TrendingUp, PieChart as PieIcon } from 'lucide-react'
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, PieChart, Pie, Cell } from 'recharts'

function KpiCard({ icon: Icon, label, value, sub, color = 'purple' }) {
  const colors = {
    purple: 'bg-purple-500/10 border-purple-500/20 text-purple-400',
    blue:   'bg-blue-500/10   border-blue-500/20   text-blue-400',
    green:  'bg-emerald-500/10 border-emerald-500/20 text-emerald-400',
    amber:  'bg-amber-500/10  border-amber-500/20  text-amber-400',
    red:    'bg-red-500/10    border-red-500/20    text-red-400',
  }
  return (
    <div className={`card ${colors[color] || colors.purple} flex flex-col gap-2 p-5`}>
      <div className="flex items-center justify-between">
        <span className="text-xs font-semibold uppercase tracking-wider opacity-70">{label}</span>
        <Icon size={18} />
      </div>
      <p className="text-3xl font-bold font-display text-white">{value ?? '—'}</p>
      {sub && <p className="text-xs opacity-60">{sub}</p>}
    </div>
  )
}

const PIE_COLORS = ['#8b5cf6', '#3b82f6', '#10b981', '#f59e0b', '#ec4899', '#6366f1']

export default function AdminDashboard() {
  const { data, isLoading } = useQuery({
    queryKey: ['admin-analytics'],
    queryFn: () => adminService.getAnalytics().then((r) => r.data),
    refetchInterval: 30_000,
  })

  if (isLoading) return <LoadingSpinner label="Loading Admin Analytics…" />

  const kpis = data?.kpis || {}
  const growth = data?.growth_chart || []
  const categories = (data?.food_categories || []).map((c, i) => ({
    name: c.category.replace('_', ' '),
    value: c.count,
    color: PIE_COLORS[i % PIE_COLORS.length],
  }))
  const activities = data?.recent_activities || []

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold font-display text-white">Creator Platform Overview</h1>
        <p className="text-xs text-slate-400">Real-time SaaS analytics, AI model usage, and system statistics</p>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <KpiCard icon={Users}     label="Total Users"       value={kpis.total_users}          sub={`${kpis.active_users_today || 0} active today`} color="purple" />
        <KpiCard icon={Calendar}  label="Meal Plans"        value={kpis.meal_plans_generated} sub="Generated by users"               color="blue"   />
        <KpiCard icon={Cpu}       label="Gemini API Requests" value={kpis.gemini_requests}    sub="Success rate 99.4%"                color="green"  />
        <KpiCard icon={Database}  label="Food Database"     value={kpis.total_foods}          sub="Verified items"                    color="amber"  />
      </div>

      {/* Charts Row */}
      <div className="grid lg:grid-cols-3 gap-6">
        {/* User Growth Line Chart */}
        <div className="card lg:col-span-2">
          <h2 className="text-sm font-semibold text-white mb-4 flex items-center gap-2">
            <TrendingUp size={15} className="text-purple-400" /> Platform Growth & Meal Plan Trends
          </h2>
          <ResponsiveContainer width="100%" height={220}>
            <LineChart data={growth}>
              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
              <XAxis dataKey="date" tick={{ fontSize: 11, fill: '#64748b' }} />
              <YAxis tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} />
              <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155', borderRadius: 8 }} />
              <Line type="monotone" dataKey="users" name="Total Users" stroke="#8b5cf6" strokeWidth={2} />
              <Line type="monotone" dataKey="plans" name="Meal Plans" stroke="#10b981" strokeWidth={2} />
            </LineChart>
          </ResponsiveContainer>
        </div>

        {/* Food Categories Pie Chart */}
        <div className="card">
          <h2 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
            <PieIcon size={15} className="text-purple-400" /> Food Category Breakdown
          </h2>
          <ResponsiveContainer width="100%" height={200}>
            <PieChart>
              <Pie data={categories} cx="50%" cy="50%" innerRadius={45} outerRadius={75} paddingAngle={4} dataKey="value">
                {categories.map((entry, index) => (
                  <Cell key={index} fill={entry.color} stroke="transparent" />
                ))}
              </Pie>
              <Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155', borderRadius: 8, fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
          <div className="flex flex-wrap justify-center gap-2 text-[10px] mt-2">
            {categories.slice(0, 5).map((c) => (
              <span key={c.name} className="flex items-center gap-1 text-slate-400">
                <span className="w-2 h-2 rounded-full" style={{ background: c.color }} /> {c.name} ({c.value})
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Activity Log Table */}
      <div className="card overflow-hidden">
        <h2 className="text-sm font-semibold text-white mb-4">Recent Audit Activity</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="border-b border-slate-800 text-slate-400 uppercase tracking-wider bg-slate-900/50">
              <tr>
                <th className="py-2.5 px-3">User</th>
                <th className="py-2.5 px-3">Action</th>
                <th className="py-2.5 px-3">Description</th>
                <th className="py-2.5 px-3">IP Address</th>
                <th className="py-2.5 px-3">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/50 text-slate-300">
              {activities.map((a) => (
                <tr key={a.id} className="hover:bg-slate-800/30">
                  <td className="py-2.5 px-3 font-medium text-white">{a.user__email || 'Anonymous'}</td>
                  <td className="py-2.5 px-3">
                    <span className="badge badge-purple text-[10px]">{a.action}</span>
                  </td>
                  <td className="py-2.5 px-3 text-slate-400">{a.description}</td>
                  <td className="py-2.5 px-3 font-mono text-[11px] text-slate-500">{a.ip_address || '—'}</td>
                  <td className="py-2.5 px-3 text-slate-500">{new Date(a.timestamp).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
