# Generated by Django 5.1.15 on 2026-07-22 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('PROFILE_UPDATED', 'Profile Updated'), ('MEAL_GENERATED', 'Meal Plan Generated'), ('PDF_DOWNLOADED', 'PDF Downloaded'), ('FAVORITE_ADDED', 'Favorite Added'), ('WATER_UPDATED', 'Water Intake Updated'), ('BMI_CALCULATED', 'BMI Calculated'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Email used during login attempt', max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(default='Desktop/Unknown', max_length=100)),
                ('os_name', models.CharField(default='Unknown OS', max_length=100)),
                ('browser_name', models.CharField(default='Unknown Browser', max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('jwt_token_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History Logs',
                'ordering': ['-login_time'],
            },
        ),
    ]
