# Generated by Django 5.1.15 on 2026-07-22 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly Active (1-3 days/week)'), ('moderate', 'Moderately Active (3-5 days/week)'), ('very', 'Very Active (6-7 days/week)'), ('extra', 'Extra Active (physical job or 2x training)')], default='moderate', max_length=20)),
                ('fitness_goal', models.CharField(choices=[('lose_fat', 'Lose Fat'), ('build_muscle', 'Build Muscle'), ('maintain', 'Maintain Weight'), ('improve_health', 'Improve Overall Health'), ('increase_endurance', 'Increase Endurance')], default='maintain', max_length=30)),
                ('food_preference', models.CharField(choices=[('none', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('gluten_free', 'Gluten-Free')], default='none', max_length=30)),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated list of allergies.')),
                ('medical_conditions', models.TextField(blank=True, help_text='Comma-separated medical conditions.')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('cuisine_preference', models.CharField(blank=True, max_length=100)),
                ('budget_per_day_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('workout_time', models.CharField(blank=True, help_text='e.g., Morning, Evening', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
